#pragma once
#define SYSCALL_BASE 10

enum
{
	ECALL_SELF_TEST = SYSCALL_BASE,
	ECALL_ASSERT_FAIL,
	ECALL_PRINT,
	ECALL_LOG,

	ECALL_REGEX_COMPILE,
	ECALL_REGEX_MATCH,
	ECALL_REGEX_SUBST,
	ECALL_REGSUB_HDR,
	ECALL_REGEX_FREE,

	ECALL_MY_NAME,
	ECALL_SET_DECISION,
	ECALL_BAN,
	ECALL_HASH_DATA,

	ECALL_FOREACH_FIELD,
	ECALL_FIELD_GET,
	ECALL_FIELD_RETRIEVE,
	ECALL_FIELD_APPEND,
	ECALL_FIELD_SET,
	ECALL_FIELD_UNSET,

	ECALL_HTTP_COPY,
	ECALL_HTTP_SET_STATUS,
	ECALL_HTTP_UNSET_RE,
	ECALL_HTTP_FIND,

	ECALL_LAST
};
