name: Ubuntu Linux 24.04

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}-ubuntu-24.04
  cancel-in-progress: true

jobs:
  native:
    name: Ubuntu Linux 24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Varnish Cache 7.6
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          curl -s https://packagecloud.io/install/repositories/varnishcache/varnish76/script.deb.sh | sudo bash
          sudo apt-get update
          sudo apt-get install -y varnish varnish-dev
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ clang ccache ninja-build libcurl4-openssl-dev libpcre3-dev libarchive-dev libjemalloc-dev
          git submodule update --init

      - name: '🚧 CCache setup'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ubuntu-linux-24.04
          max-size: 200M

      - name: Configure
        env:
          CC: ccache clang
          CXX: ccache clang++
        run: >
          cmake -S. -Bbuild
          -G Ninja
          -DCMAKE_BUILD_TYPE=DebWithRelInfo
          -DVARNISH_PLUS=OFF
          -DPython3_EXECUTABLE=$(which python3)
      - name: Build
        run: >
          cmake --build build
          --config DebWithRelInfo
          --target all
          -v -j4
          && mkdir -p ubuntu-linux-24.04
          && mv build/libvmod_* ubuntu-linux-24.04
          && tar -czf ubuntu-linux-24.04.tar.gz ubuntu-linux-24.04

      - uses: actions/upload-artifact@v4
        with:
          name: build-ubuntu-linux-24.04
          path: ./ubuntu-linux-24.04.tar.gz
          overwrite: true
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          retention-days: 1 # 90 days by default
